export const GAME_END = 'GAME_END';

export const GAME_START = 'GAME_START';

export const HALT_INPUT = 'HALT_INPUT';

export const ALLOW_INPUT = 'ALLOW_INPUT';

export const BUTTON_PRESS = 'BUTTON_PRESS';

export const ADD_TO_PLAYBACK_SEQUENCE = "ADD_TO_PLAYBACK_SEQUENCE";

export const GAME_CHANGE_COLOR_SCHEME = 'GAME_CHANGE_COLOR_SCHEME';
