export const GAME_END = 'GAME_END';
export const INC_SCORE = 'INC_SCORE';
export const GAME_START = 'GAME_START';
export const WRONG_ENTRY = 'WRONG_ENTRY';
export const BUTTON_PRESS = 'BUTTON_PRESS';
export const ADD_TO_PLAYBACK_SEQUENCE = "ADD_TO_PLAYBACK_SEQUENCE";
export const GAME_CHANGE_COLOR_SCHEME = 'GAME_CHANGE_COLOR_SCHEME';